name: integration-test
on:
  push:
    branches:
      - master
      - test-actions # REMOVE ME
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]
    branches:
      - master
      - test-actions # REMOVE ME
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      EVENT: github.event_type
    steps:
      - name: testing
        run: |
          echo $EVENT
  labeler:
    if: | # Add/Re-Add need:ok-to-test anytime there's a commit or PR is opened
      github.event_type == 'opened' ||
      github.event_type == 'synchronize' ||
      github.event_type == 'reopened'
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
  integration-test:
    needs: labeler # Prevent Running integration test until labeler has run
    name: integration-test
    runs-on: self-hosted
    env:
      CLUSTER_NAME: vpc-rc-ci-test
      K8S_VERSION: 1.19
    if: | # Run test only when ok-to-test is added and needs:ok-to-test removed
      (github.event_type == 'labeled' ||
      github.event_type == 'unlabeled') &&
      (contains(github.event.pull_request.labels.*.name, 'ok-to-test') &&
      !contains(github.event.pull_request.labels.*.name, 'needs:ok-to-test'))
    steps:
      - name: clean work dir from previous runs
        run: |
          rm -rf *
      - name: setup go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: setup environment
        run: |
          source ~/.bashrc
      - name: checkout code
        uses: actions/checkout@v2
      - name: clean docker images
        run: docker image prune -f
      - name: create EKS Cluster
        run: |
          ./scripts/test/create-cluster.sh \
            -n $CLUSTER_NAME \
            -v $K8S_VERSION \
            -s $GITHUB_RUN_NUMBER
      - name: create IAM Roles
        run: |
          ./scripts/test/iam-resources.sh \
            -n $CLUSTER_NAME \
            -s $GITHUB_RUN_NUMBER \
            -o "create"
      - name: run integration tests
        run: |
          ./scripts/test/test-with-eksctl.sh \
            -n $CLUSTER_NAME \
            -s $GITHUB_RUN_NUMBER
      - name: delete IAM Roles
        if: always()
        run: |
          ./scripts/test/iam-resources.sh \
            -n $CLUSTER_NAME \
            -s $GITHUB_RUN_NUMBER \
            -o "delete"
      - name: delete EKS Cluster
        id: deleteCluster
        if: always()
        run: |
          ./scripts/test/delete-cluster.sh
